name: Release
on:
  workflow_dispatch: # trigger the Release workflow manually
  push:
    tags:
      - '*' # trigger the Release workflow on tag creation
jobs:
  rspec:
    uses: ./.github/workflows/rspec.yml
  build:
    name: Build + Publish
    needs: [rspec]  # require rspec to pass before build runs
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Setup up node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          mkdir ../assets
          cp -r ./build/* ../assets

      - name: Configure credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          echo -e ":rubygems_api_key: ${GEM_HOST_API_KEY}" > $HOME/.gem/credentials
          echo -e ":github: ${RUBYGEMS_API_KEY}" > $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

      - name: Build gem
        run: |
          gem build *.gemspec

      - name: Publish to GPR & RubyGems
        run: |
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
          gem push *.gem --host https://rubygems.org
        env:
          OWNER: ${{ github.repository_owner }}
