name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup up node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
      - name: Create .gem/credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
      - name: Publish to GPR
        run: |
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build lowkiq.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} lowkiq.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
      - name: Publish to RubyGems
        run: |
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build lowkiq.gemspec
          gem push lowkiq.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"